package com.weixin.impl.mapper;

import com.github.pagehelper.Page;
import com.weixin.api.po.MessageboardHuifu;
import com.weixin.vo.MessageboardSearchParam;

public interface MessageboardHuifuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messageboard_huifu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messageboard_huifu
	 * @mbg.generated
	 */
	int insert(MessageboardHuifu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messageboard_huifu
	 * @mbg.generated
	 */
	int insertSelective(MessageboardHuifu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messageboard_huifu
	 * @mbg.generated
	 */
	MessageboardHuifu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messageboard_huifu
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MessageboardHuifu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messageboard_huifu
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MessageboardHuifu record);

	Page<MessageboardHuifu> getLiuYanHuiFuList(MessageboardSearchParam searchParam);

	Integer getPingLunCountByMsgID(Integer id);
}