package com.weixin.impl.mapper;

import com.github.pagehelper.Page;
import com.weixin.api.po.YzcxQxusers;
import org.apache.ibatis.annotations.Param;

public interface YzcxQxusersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yzcx_qxusers
	 * 
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yzcx_qxusers
	 * 
	 * @mbg.generated
	 */
	int insert(YzcxQxusers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yzcx_qxusers
	 * 
	 * @mbg.generated
	 */
	int insertSelective(YzcxQxusers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yzcx_qxusers
	 * 
	 * @mbg.generated
	 */
	YzcxQxusers selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yzcx_qxusers
	 * 
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(YzcxQxusers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yzcx_qxusers
	 * 
	 * @mbg.generated
	 */
	int updateByPrimaryKey(YzcxQxusers record);

	Integer selectByWXUserID(String userid);

	int updateByByWXUserIDSelective(YzcxQxusers qxuser);

	Page<YzcxQxusers> selectQXUsers();

	int delQXUserByIDS(@Param("ids") String[] ids);
}