package com.weixin.impl.mapper;

import com.weixin.api.po.YzcxQxlist;

import java.util.List;

public interface YzcxQxlistMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yzcx_qxlist
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yzcx_qxlist
	 * @mbg.generated
	 */
	int insert(YzcxQxlist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yzcx_qxlist
	 * @mbg.generated
	 */
	int insertSelective(YzcxQxlist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yzcx_qxlist
	 * @mbg.generated
	 */
	YzcxQxlist selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yzcx_qxlist
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(YzcxQxlist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yzcx_qxlist
	 * @mbg.generated
	 */
	int updateByPrimaryKey(YzcxQxlist record);

	List<YzcxQxlist> selectAllList();
}