package com.weixin.api.po;

import java.util.Date;

public class MessageboardHuifu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_huifu.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_huifu.messageid
	 * @mbg.generated
	 */
	private Integer messageid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_huifu.hfnr
	 * @mbg.generated
	 */
	private String hfnr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_huifu.createtime
	 * @mbg.generated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_huifu.wxqyuserid
	 * @mbg.generated
	 */
	private String wxqyuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_huifu.wxqyusername
	 * @mbg.generated
	 */
	private String wxqyusername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_huifu.wxheadimg
	 * @mbg.generated
	 */
	private String wxheadimg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_huifu.id
	 * @return  the value of messageboard_huifu.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_huifu.id
	 * @param id  the value for messageboard_huifu.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_huifu.messageid
	 * @return  the value of messageboard_huifu.messageid
	 * @mbg.generated
	 */
	public Integer getMessageid() {
		return messageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_huifu.messageid
	 * @param messageid  the value for messageboard_huifu.messageid
	 * @mbg.generated
	 */
	public void setMessageid(Integer messageid) {
		this.messageid = messageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_huifu.hfnr
	 * @return  the value of messageboard_huifu.hfnr
	 * @mbg.generated
	 */
	public String getHfnr() {
		return hfnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_huifu.hfnr
	 * @param hfnr  the value for messageboard_huifu.hfnr
	 * @mbg.generated
	 */
	public void setHfnr(String hfnr) {
		this.hfnr = hfnr == null ? null : hfnr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_huifu.createtime
	 * @return  the value of messageboard_huifu.createtime
	 * @mbg.generated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_huifu.createtime
	 * @param createtime  the value for messageboard_huifu.createtime
	 * @mbg.generated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_huifu.wxqyuserid
	 * @return  the value of messageboard_huifu.wxqyuserid
	 * @mbg.generated
	 */
	public String getWxqyuserid() {
		return wxqyuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_huifu.wxqyuserid
	 * @param wxqyuserid  the value for messageboard_huifu.wxqyuserid
	 * @mbg.generated
	 */
	public void setWxqyuserid(String wxqyuserid) {
		this.wxqyuserid = wxqyuserid == null ? null : wxqyuserid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_huifu.wxqyusername
	 * @return  the value of messageboard_huifu.wxqyusername
	 * @mbg.generated
	 */
	public String getWxqyusername() {
		return wxqyusername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_huifu.wxqyusername
	 * @param wxqyusername  the value for messageboard_huifu.wxqyusername
	 * @mbg.generated
	 */
	public void setWxqyusername(String wxqyusername) {
		this.wxqyusername = wxqyusername == null ? null : wxqyusername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_huifu.wxheadimg
	 * @return  the value of messageboard_huifu.wxheadimg
	 * @mbg.generated
	 */
	public String getWxheadimg() {
		return wxheadimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_huifu.wxheadimg
	 * @param wxheadimg  the value for messageboard_huifu.wxheadimg
	 * @mbg.generated
	 */
	public void setWxheadimg(String wxheadimg) {
		this.wxheadimg = wxheadimg == null ? null : wxheadimg.trim();
	}

	@Override
	public String toString() {
		return "MessageboardHuifu [id=" + id + ", messageid=" + messageid + ", hfnr=" + hfnr + ", createtime="
				+ createtime + ", wxqyuserid=" + wxqyuserid + ", wxqyusername=" + wxqyusername + ", wxheadimg="
				+ wxheadimg + "]";
	}
	
}