package com.weixin.api.po;

import java.util.Date;

public class MessageboardMessage {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_message.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_message.wxqyuserid
	 * @mbg.generated
	 */
	private String wxqyuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_message.wxqyusername
	 * @mbg.generated
	 */
	private String wxqyusername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_message.wxheadimg
	 * @mbg.generated
	 */
	private String wxheadimg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_message.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_message.content
	 * @mbg.generated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_message.messageimages
	 * @mbg.generated
	 */
	private String messageimages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageboard_message.createtime
	 * @mbg.generated
	 */
	private Date createtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_message.id
	 * @return  the value of messageboard_message.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_message.id
	 * @param id  the value for messageboard_message.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_message.wxqyuserid
	 * @return  the value of messageboard_message.wxqyuserid
	 * @mbg.generated
	 */
	public String getWxqyuserid() {
		return wxqyuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_message.wxqyuserid
	 * @param wxqyuserid  the value for messageboard_message.wxqyuserid
	 * @mbg.generated
	 */
	public void setWxqyuserid(String wxqyuserid) {
		this.wxqyuserid = wxqyuserid == null ? null : wxqyuserid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_message.wxqyusername
	 * @return  the value of messageboard_message.wxqyusername
	 * @mbg.generated
	 */
	public String getWxqyusername() {
		return wxqyusername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_message.wxqyusername
	 * @param wxqyusername  the value for messageboard_message.wxqyusername
	 * @mbg.generated
	 */
	public void setWxqyusername(String wxqyusername) {
		this.wxqyusername = wxqyusername == null ? null : wxqyusername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_message.wxheadimg
	 * @return  the value of messageboard_message.wxheadimg
	 * @mbg.generated
	 */
	public String getWxheadimg() {
		return wxheadimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_message.wxheadimg
	 * @param wxheadimg  the value for messageboard_message.wxheadimg
	 * @mbg.generated
	 */
	public void setWxheadimg(String wxheadimg) {
		this.wxheadimg = wxheadimg == null ? null : wxheadimg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_message.title
	 * @return  the value of messageboard_message.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_message.title
	 * @param title  the value for messageboard_message.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_message.content
	 * @return  the value of messageboard_message.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_message.content
	 * @param content  the value for messageboard_message.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_message.messageimages
	 * @return  the value of messageboard_message.messageimages
	 * @mbg.generated
	 */
	public String getMessageimages() {
		return messageimages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_message.messageimages
	 * @param messageimages  the value for messageboard_message.messageimages
	 * @mbg.generated
	 */
	public void setMessageimages(String messageimages) {
		this.messageimages = messageimages == null ? null : messageimages.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageboard_message.createtime
	 * @return  the value of messageboard_message.createtime
	 * @mbg.generated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageboard_message.createtime
	 * @param createtime  the value for messageboard_message.createtime
	 * @mbg.generated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Override
	public String toString() {
		return "MessageboardMessage [id=" + id + ", wxqyuserid=" + wxqyuserid + ", wxqyusername=" + wxqyusername
				+ ", wxheadimg=" + wxheadimg + ", title=" + title + ", content=" + content + ", messageimages="
				+ messageimages + ", createtime=" + createtime + "]";
	}

}