package com.weixin.api.po;

public class YzcxQxlist {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yzcx_qxlist.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yzcx_qxlist.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yzcx_qxlist.keynum
	 * @mbg.generated
	 */
	private String keynum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yzcx_qxlist.id
	 * @return  the value of yzcx_qxlist.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yzcx_qxlist.id
	 * @param id  the value for yzcx_qxlist.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yzcx_qxlist.name
	 * @return  the value of yzcx_qxlist.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yzcx_qxlist.name
	 * @param name  the value for yzcx_qxlist.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yzcx_qxlist.keynum
	 * @return  the value of yzcx_qxlist.keynum
	 * @mbg.generated
	 */
	public String getKeynum() {
		return keynum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yzcx_qxlist.keynum
	 * @param keynum  the value for yzcx_qxlist.keynum
	 * @mbg.generated
	 */
	public void setKeynum(String keynum) {
		this.keynum = keynum == null ? null : keynum.trim();
	}
}